name: 'Set chart info'
inputs:
  chart_dir:
    required: true
  chart_name:
    required: true
  chart_description:
    required: false
    default: ''
  chart_version:
    required: false
    default: ''
  docker_image_url:
    required: false
    default: ''
  shared_chart_name:
    required: false
    default: ''
  shared_chart_version:
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    - 
      name: Update Helm chart name
      uses: fjogeleit/yaml-update-action@master
      with:
        workDir: '${{ inputs.chart_dir }}/${{ inputs.chart_name }}'
        valueFile: 'Chart.yaml'
        propertyPath: 'name'
        value: '${{ inputs.chart_name }}'
        commitChange: 'false'
        updateFile: 'true'
    - 
      name: Update Helm chart version
      uses: fjogeleit/yaml-update-action@master
      with:
        workDir: '${{ inputs.chart_dir }}/${{ inputs.chart_name }}'
        valueFile: 'Chart.yaml'
        propertyPath: 'version'
        value: '${{ inputs.chart_version }}'
        commitChange: 'false'
        updateFile: 'true'
    - 
      # conditionals workaround
      uses: ChristopherHX/conditional@b4a9649204f81002ec9a4ef7d4bf7d6b2ab7fa55
      with:
        if: ${{ inputs.shared_chart_name != '' }}
        step: |
          name: Update Helm shared chart name
          uses: fjogeleit/yaml-update-action@master
          with:
            workDir: '${{ inputs.chart_dir }}/${{ inputs.chart_name }}'
            valueFile: 'Chart.yaml'
            propertyPath: 'dependencies.0.name'
            value: '${{ inputs.shared_chart_name }}'
            commitChange: 'false'
            updateFile: 'true'
    - 
      # conditionals workaround
      uses: ChristopherHX/conditional@b4a9649204f81002ec9a4ef7d4bf7d6b2ab7fa55
      with:
        if: ${{ inputs.shared_chart_version != '' }}
        step: |
          name: Update Helm shared chart version
          uses: fjogeleit/yaml-update-action@master
          with:
            workDir: '${{ inputs.chart_dir }}/${{ inputs.chart_name }}'
            valueFile: 'Chart.yaml'
            propertyPath: 'dependencies.0.version'
            value: '${{ inputs.shared_chart_version }}'
            commitChange: 'false'
            updateFile: 'true'
    - 
      # conditionals workaround
      uses: ChristopherHX/conditional@b4a9649204f81002ec9a4ef7d4bf7d6b2ab7fa55
      with:
        if: ${{ inputs.chart_description != '' }}
        step: |
          name: Update Helm chart description
          uses: fjogeleit/yaml-update-action@master
          with:
            workDir: '${{ inputs.chart_dir }}/${{ inputs.chart_name }}'
            valueFile: 'Chart.yaml'
            propertyPath: 'description'
            value: '${{ inputs.chart_description }}'
            commitChange: 'false'
            updateFile: 'true'
    - 
      # conditionals workaround
      uses: ChristopherHX/conditional@b4a9649204f81002ec9a4ef7d4bf7d6b2ab7fa55
      with:
        if: ${{ inputs.docker_image_url != '' }}
        step: |
          name: Update Helm chart description
          uses: fjogeleit/yaml-update-action@master
          with:
            workDir: '${{ inputs.chart_dir }}/${{ inputs.chart_name }}'
            valueFile: 'values.yaml'
            propertyPath: 'image.repository'
            value: '${{ inputs.docker_image_url }}'
            commitChange: 'false'
            updateFile: 'true'