name: 'Set chart info'
inputs:
  chart_dir:
    required: true
  chart_name:
    required: true
  chart_description:
    required: false
    default: ''
  chart_version:
    required: false
    default: ''
  chart_app_version:
    required: false
    default: ''
  docker_image_url:
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    - 
      name: Update Helm chart name
      uses: fjogeleit/yaml-update-action@master
      with:
        workDir: ${{ inputs.chart_dir }}
        valueFile: 'Chart.yaml'
        propertyPath: 'name'
        value: ${{ inputs.chart_name }}
        commitChange: false
        updateFile: true
    - 
      name: Update Helm chart version
      uses: fjogeleit/yaml-update-action@master
      with:
        workDir: ${{ inputs.chart_dir }}
        valueFile: 'Chart.yaml'
        propertyPath: 'version'
        value: ${{ inputs.chart_version }}
        commitChange: false
        updateFile: true
    - 
      # conditionals workaround
      name: Set chart app version
      uses: ChristopherHX/conditional@b4a9649204f81002ec9a4ef7d4bf7d6b2ab7fa55
      with:
        if: ${{ inputs.chart_app_version != '' }}
        step: |
          name: Update Helm app version
          uses: fjogeleit/yaml-update-action@master
          with:
            workDir: ${{ inputs.chart_dir }}
            valueFile: 'Chart.yaml'
            propertyPath: 'appVersion'
            value: ${{ inputs.chart_app_version }}
            commitChange: false
            updateFile: true
    - 
      # conditionals workaround
      name: Set chart description
      uses: ChristopherHX/conditional@b4a9649204f81002ec9a4ef7d4bf7d6b2ab7fa55
      with:
        if: ${{ inputs.chart_description != '' }}
        step: |
          name: Update Helm chart description
          uses: fjogeleit/yaml-update-action@master
          with:
            workDir: ${{ inputs.chart_dir }}
            valueFile: 'Chart.yaml'
            propertyPath: 'description'
            value: ${{ inputs.chart_description }}
            commitChange: false
            updateFile: true
    -
      name: test_before
      run: cat ${{ inputs.chart_dir }}/values.yaml
    - 
      # conditionals workaround
      name: Set Docker image url
      uses: ChristopherHX/conditional@b4a9649204f81002ec9a4ef7d4bf7d6b2ab7fa55
      with:
        if: ${{ inputs.docker_image_url != '' }}
        step: |
          name: Update Helm chart description
          uses: fjogeleit/yaml-update-action@master
          with:
            workDir: ${{ inputs.chart_dir }}
            valueFile: 'values.yaml'
            propertyPath: 'image.repository'
            value: ${{ inputs.docker_image_url }}
            commitChange: false
            updateFile: true
    -
      name: test_after
      run: cat ${{ inputs.chart_dir }}/values.yaml