name: 'Set chart info'
inputs:
  chart_dir:
    required: true
  chart_name:
    required: true
  chart_description:
    required: false
    default: ''
  chart_version:
    required: false
    default: ''
  chart_app_version:
    required: false
    default: ''
  docker_image_url:
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    -
      name: Install YQ
      uses: Geta/gks/actions/setup-yq@actions/v1
    - 
      name: Update Helm chart name
      shell: bash
      run: |
        ./yq e '.name = "${{ inputs.chart_name }}"' -i '${{ inputs.chart_dir }}/Chart.yaml'
    - 
      name: Update Helm chart version
      shell: bash
      run: |
        ./yq e '.version = "${{ inputs.chart_version }}"' -i '${{ inputs.chart_dir }}/Chart.yaml'
    - 
      # conditionals workaround
      name: Set chart app version
      uses: ChristopherHX/conditional@b4a9649204f81002ec9a4ef7d4bf7d6b2ab7fa55
      with:
        if: ${{ inputs.chart_app_version != '' }}
        step: |
          shell: bash
          run: |
            ./yq e '.appVersion = "${{ inputs.chart_app_version }}"' -i '${{ inputs.chart_dir }}/Chart.yaml'
    - 
      # conditionals workaround
      name: Set chart description
      uses: ChristopherHX/conditional@b4a9649204f81002ec9a4ef7d4bf7d6b2ab7fa55
      with:
        if: ${{ inputs.chart_description != '' }}
        step: |
          shell: bash
          run: |
            ./yq e '.description = "${{ inputs.chart_description }}"' -i '${{ inputs.chart_dir }}/Chart.yaml'
    - 
      # conditionals workaround
      name: Set Docker image url
      uses: ChristopherHX/conditional@b4a9649204f81002ec9a4ef7d4bf7d6b2ab7fa55
      with:
        if: ${{ inputs.docker_image_url != '' }}
        step: |
          shell: bash
          run: |
            ./yq e '.image.repository = "${{ inputs.docker_image_url }}"' -i '${{ inputs.chart_dir }}/values.yaml'
