name: 'Set chart info'
inputs:
  chart_dir:
    required: true
  chart_name:
    required: true
  chart_description:
    required: false
    default: ''
  chart_version:
    required: false
    default: ''
  chart_app_version:
    required: false
    default: ''
  docker_image_url:
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    -
      name: Install YQ
      uses: chrisdickinson/setup-yq@latest
    - 
      name: Update Helm chart name
      shell: bash
      run: |
        yq w '${{ inputs.chart_dir }}/Chart.yaml' 'name' '${{ inputs.chart_name }}'
    - 
      name: Update Helm chart version
      shell: bash
      run: |
        yq w '${{ inputs.chart_dir }}/Chart.yaml' 'version' '${{ inputs.chart_version }}'
    - 
      # conditionals workaround
      name: Set chart app version
      uses: ChristopherHX/conditional@b4a9649204f81002ec9a4ef7d4bf7d6b2ab7fa55
      with:
        if: ${{ inputs.chart_app_version != '' }}
        step: |
          shell: bash
          run: |
            yq w '${{ inputs.chart_dir }}/Chart.yaml' 'appVersion' '${{ inputs.chart_app_version }}'
    - 
      # conditionals workaround
      name: Set chart description
      uses: ChristopherHX/conditional@b4a9649204f81002ec9a4ef7d4bf7d6b2ab7fa55
      with:
        if: ${{ inputs.chart_description != '' }}
        step: |
          shell: bash
          run: |
            yq w '${{ inputs.chart_dir }}/Chart.yaml' 'description' '${{ inputs.chart_description }}'
    - 
      # conditionals workaround
      name: Set Docker image url
      uses: ChristopherHX/conditional@b4a9649204f81002ec9a4ef7d4bf7d6b2ab7fa55
      with:
        if: ${{ inputs.docker_image_url != '' }}
        step: |
          shell: bash
          run: |
            yq w '${{ inputs.chart_dir }}/values.yaml' 'image.repository' '${{ inputs.docker_image_url }}'
