name: 'Set Up Helm'
inputs:
  helm_repository_url:
    required: true
  helm_repository_user:
    required: true
  helm_repository_token:
    required: true
  helm_repository_project:
    required: true
  helm_repository_project2:
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    -
      name: Install Helm
      uses: azure/setup-helm@v1
    -
      name: Install Helm Push plugin
      shell: bash
      run: helm plugin install https://github.com/chartmuseum/helm-push.git
    -
      name: Add project Helm repository
      shell: bash
      run: helm repo add --username '${{ inputs.helm_repository_user }}' --password '${{ inputs.helm_repository_token }}' ${{ inputs.helm_repository_project }} ${{ inputs.helm_repository_url }}/${{ inputs.helm_repository_project }}
    - 
      # conditionals workaround
      uses: ChristopherHX/conditional@b4a9649204f81002ec9a4ef7d4bf7d6b2ab7fa55
      with:
        if: ${{ inputs.helm_repository_project2 != '' }}
        step: |
          name: Add additional Helm repository
          shell: bash
          run: helm repo add --username '${{ inputs.helm_repository_user }}' --password '${{ inputs.helm_repository_token }}' ${{ inputs.helm_repository_project2 }} ${{ inputs.helm_repository_url }}/${{ inputs.helm_repository_project2 }}
    - 
      name: Update repositories
      shell: bash
      run: helm repo update