name: 'Run Preconfiguration'
inputs:
  file:
    required: false
    description: 'Configuration file path'
    default: '.github/config.yaml'
outputs:
  app_name: 
    value: '${{ steps.appname.outputs.data }}'
  dockerfile:
    value: '${{ steps.dockerfile.outputs.data }}'
runs:
  using: "composite"
  steps:
    -
      name: Read application name
      uses: KJ002/read-yaml@1.5
      id: appname
      with:
        file: '${{ inputs.file }}'
        key-path: '["app", "name"]'
    -
      name: Read application name
      uses: KJ002/read-yaml@1.5
      id: dockerfile
      with:
        file: '${{ inputs.file }}'
        key-path: '["app", "dockerfile"]'