name: 'Run Preconfiguration'
inputs:
  file:
    required: false
    description: 'Configuration file path'
    default: '.github/config.yaml'
outputs:
  app_name: 
    value: ${{ steps.app_name.outputs.data }}
  app_dockerfile:
    value: ${{ steps.app_dockerfile.outputs.data }}
  app_packages_url:
    value: ${{ steps.app_packages_url.outputs.data }}
  app_docker_context:
    value: ${{ steps.app_docker_context.outputs.data }}

  harbor_project:
    value: ${{ steps.harbor_project.outputs.data }}
  harbor_proxy_project:
    value: ${{ steps.harbor_proxy_project.outputs.data }}
  harbor_helm_template:
    value: ${{ steps.harbor_helm_template.outputs.data }}
  harbor_domain:
    value: ${{ steps.harbor_domain.outputs.data }}

  git_submodules:
    value: ${{ steps.git_submodules.outputs.data }}

  sonarqube_execute:
    value: ${{ steps.sonarqube_execute.outputs.data }}
  sonarqube_project:
    value: ${{ steps.sonarqube_project.outputs.data }}
  sonarqube_validate:
    value: ${{ steps.sonarqube_validate.outputs.data }}
  sonarqube_platform:
    value: ${{ steps.sonarqube_platform.outputs.data }}
  sonarqube_exclusions:
    value: ${{ steps.sonarqube_exclusions.outputs.data }}
  sonarqube_dotnet:
    value: ${{ steps.sonarqube_dotnet.outputs.data }}
  sonarqube_domain:
    value: ${{ steps.sonarqube_domain.outputs.data }}

  docker_execute:
    value: ${{ steps.docker_execute.outputs.data }}
  docker_severity:
    value: ${{ steps.docker_severity.outputs.data }}
  docker_quality:
    value: ${{ steps.docker_quality.outputs.data }}
runs:
  using: "composite"
  steps:
    -
      name: Install YQ
      uses: Geta/gks/actions/setup-yq@actions/v1

    -
      name: Read application name
      id: app_name
      uses: Geta/gks/actions/read-yaml-field@actions/v1
      with:
        path: '.app.name'
        file: ${{ inputs.file }}
    -
      name: Read Dockerfile path
      id: app_dockerfile
      uses: Geta/gks/actions/read-yaml-field@actions/v1
      with:
        path: '.app.dockerfile'
        file: ${{ inputs.file }}
    -
      name: Read packages url
      id: app_packages_url
      uses: Geta/gks/actions/read-yaml-field@actions/v1
      with:
        path: '.app.packages_url'
        file: ${{ inputs.file }}
    -
      name: Read docker context dir
      id: app_docker_context
      uses: Geta/gks/actions/read-yaml-field@actions/v1
      with:
        path: '.app.docker_context'
        file: ${{ inputs.file }}

    -
      name: Read Harbor project name
      id: harbor_project
      uses: Geta/gks/actions/read-yaml-field@actions/v1
      with:
        path: '.harbor.project'
        file: ${{ inputs.file }}
    -
      name: Read Harbor proxy project name
      id: harbor_proxy_project
      uses: Geta/gks/actions/read-yaml-field@actions/v1
      with:
        path: '.harbor.proxy_project'
        file: ${{ inputs.file }}
    -
      name: Read Harbor Helm template version
      id: harbor_helm_template
      uses: Geta/gks/actions/read-yaml-field@actions/v1
      with:
        path: '.harbor.helm_template'
        file: ${{ inputs.file }}
    -
      name: Read Harbor domain name
      id: harbor_domain
      uses: Geta/gks/actions/read-yaml-field@actions/v1
      with:
        path: '.harbor.domain'
        file: ${{ inputs.file }}

    -
      name: Read Git sumbodules flag
      id: git_submodules
      uses: Geta/gks/actions/read-yaml-field@actions/v1
      with:
        path: '.git.submodules'
        file: ${{ inputs.file }}

    -
      name: Read SonarQube execution flag
      id: sonarqube_execute
      uses: Geta/gks/actions/read-yaml-field@actions/v1
      with:
        path: '.analysis.sonarqube.execute'
        file: ${{ inputs.file }}
    -
      name: Read SonarQube project name
      id: sonarqube_project
      uses: Geta/gks/actions/read-yaml-field@actions/v1
      with:
        path: '.analysis.sonarqube.project'
        file: ${{ inputs.file }}
    -
      name: Read SonarQube validation flag
      id: sonarqube_validate
      uses: Geta/gks/actions/read-yaml-field@actions/v1
      with:
        path: '.analysis.sonarqube.validate'
        file: ${{ inputs.file }}
    -
      name: Read SonarQube platform
      id: sonarqube_platform
      uses: Geta/gks/actions/read-yaml-field@actions/v1
      with:
        path: '.analysis.sonarqube.platform'
        file: ${{ inputs.file }}
    -
      name: Read SonarQube exclusions
      id: sonarqube_exclusions
      uses: Geta/gks/actions/read-yaml-field@actions/v1
      with:
        path: '.analysis.sonarqube.exclusions'
        file: ${{ inputs.file }}
    -
      name: Read SonarQube dotnet version
      id: sonarqube_dotnet
      uses: Geta/gks/actions/read-yaml-field@actions/v1
      with:
        path: '.analysis.sonarqube.dotnet_version'
        file: ${{ inputs.file }}
    -
      name: Read SonaQube domain name
      id: sonarqube_domain
      uses: Geta/gks/actions/read-yaml-field@actions/v1
      with:
        path: '.analysis.sonarqube.domain'
        file: ${{ inputs.file }}

    -
      name: Read Docker execution flag
      id: docker_execute
      uses: Geta/gks/actions/read-yaml-field@actions/v1
      with:
        path: '.analysis.docker.execute'
        file: ${{ inputs.file }}
    -
      name: Read Docker severity
      id: docker_severity
      uses: Geta/gks/actions/read-yaml-field@actions/v1
      with:
        path: '.analysis.docker.severity'
        file: ${{ inputs.file }}
    -
      name: Read Docker dockerfile check flag
      id: docker_quality
      uses: Geta/gks/actions/read-yaml-field@actions/v1
      with:
        path: '.analysis.docker.dockerfile_check'
        file: ${{ inputs.file }}