name: Release GKS Template Chart
on:
  workflow_call:
    inputs:
      template_chart_name:
        required: true
        type: string
      shared_chart_name:
        required: true
        type: string
      shared_chart_version:
        required: true
        type: string
      chart_path:
        required: true
        type: string
      repo_project:
        required: true
        type: string
    secrets:
      GKS_HARBOR_ADDRESS:
        required: true
      GKS_GH_ACCESS_TOKEN:
        required: true
      GKS_HARBOR_USER:
        required: true
      GKS_HARBOR_PASSWORD:
        required: true
jobs:
  build-template:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout develop branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          token: ${{ secrets.GKS_GH_ACCESS_TOKEN }}
      -
        name: Set up Helm
        uses: Geta/gks/actions/setup-helm@actions/v1
        with:
          helm_repository_url: 'https://${{ secrets.GKS_HARBOR_ADDRESS }}/chartrepo'
          helm_repository_user: ${{ secrets.GKS_HARBOR_USER }}
          helm_repository_token: ${{ secrets.GKS_HARBOR_PASSWORD }}
          helm_repository_project: ${{ inputs.repo_project }}
      -
        name: Set template Helm chart info
        uses: Geta/gks/actions/set-chart-info@actions/v1
        with:
          chart_dir: ${{ inputs.chart_path }}
          chart_name: ${{ inputs.template_chart_name }}
          chart_description: 'Chart template'
          chart_version: ${{ inputs.shared_chart_version }}
          shared_chart_name: ${{ inputs.shared_chart_name }}
          shared_chart_version: ${{ inputs.shared_chart_version }}
      -
        name: Push template Helm chart
        uses: Geta/gks/actions/package-helm-chart@actions/v1
        with:
          chart_dir: ${{ inputs.chart_path }}
          chart_name: ${{ inputs.template_chart_name }}
          chart_version: ${{ inputs.shared_chart_version }}
          helm_repository_project: ${{ inputs.repo_project }}
          push: true

