name: 'Promote Docker image'
inputs:
  repo_domain:
    required: true
  repo_user:
    required: true
  repo_token:
    required: true
  repo_project:
    required: true
  repo_name:
    required: true
  env_from:
    required: true
  env_to:
    required: true
  version:
    required: true
outputs:
  image_name:
    value: ${{ steps.promote.outputs.image_name }}
runs:
  using: "composite"
  steps:
    - 
      name: Pull latest Docker image build for version '${{ inputs.version }}'
      id: pull
      shell: bash
      env:
        DOCKER_API_URL: 'https://${{ inputs.repo_domain }}/v2/${{ inputs.repo_project }}/${{ inputs.repo_name }}/${{ inputs.env_from }}/tags/list'
      run: |
        RESPONSE=$(curl -u '${{ inputs.repo_user }}:${{ inputs.repo_token }}' --request GET '${{ env.DOCKER_API_URL }}')
        BUILD=$(echo $RESPONSE | jq .tags | sed 's/${{ inputs.version }}.//g' | sed 's/[ ,\"]//g' | sort --version-sort -r | head -1)
        TAG='${{ inputs.repo_domain }}/${{ inputs.repo_project }}/${{ inputs.repo_name }}/${{ inputs.env_from }}:${{ inputs.version }}'
        docker pull "$TAG.$BUILD"
        echo ::set-output name=latest_tag::$TAG
        echo ::set-output name=latest_build::$BUILD
    -
      name: Promote latest Docker image
      id: promote
      shell: bash
      env:
        SOURCE_IMAGE: '${{ steps.pull.outputs.latest_tag }}.${{ steps.pull.outputs.latest_build }}'
        DESTINATION_IMAGE: '${{ inputs.repo_domain }}/${{ inputs.repo_project }}/${{ inputs.repo_name }}/${{ inputs.env_to }}'
      run: |
        docker tag '${{ env.SOURCE_IMAGE }}' '${{ env.DESTINATION_IMAGE }}:${{ inputs.version }}'
        docker tag '${{ env.SOURCE_IMAGE }}' '${{ env.DESTINATION_IMAGE }}:latest'
        docker push "${{ env.DESTINATION_IMAGE }}:${{ inputs.version }}"
        docker push '${{ env.DESTINATION_IMAGE }}:latest'
        echo ::set-output name=image_name::${{ env.DESTINATION_IMAGE }}
