name: 'Package Helm Chart'
inputs:
  chart_dir:
    required: true
  chart_name:
    required: true
  chart_version:
    required: true
  push:
    required: false
    default: false
  repo_alias:
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    - 
      id: package
      name: Package Helm chart
      shell: bash
      env:
        OUT_DIR: 'output'
      run: |
        helm package '${{ inputs.chart_dir }}' --app-version '${{ inputs.chart_version }}' --version '${{ inputs.chart_version }}' --dependency-update --destination '${{ inputs.chart_dir }}/${{ env.OUT_DIR }}'
        CHART='${{ inputs.chart_dir }}/${{ env.OUT_DIR }}/${{ inputs.chart_name }}-${{ inputs.chart_version }}.tgz'
        echo "CHART_PACKAGE=$CHART" >> $GITHUB_OUTPUT
    - 
      # conditionals workaround
      uses: ChristopherHX/conditional@b4a9649204f81002ec9a4ef7d4bf7d6b2ab7fa55
      with:
        if: ${{ inputs.push == 'true' }}
        step: |
          name: Push Helm chart to registry
          shell: bash
          run: helm cm-push '${{ steps.package.outputs.CHART_PACKAGE }}' '${{ inputs.repo_alias }}'