name: Branch synchronization
on:
  workflow_call:
    inputs:
      git_ref:
        required: true
        type: string
        description: 'Git reference'
      submodules:
        required: false
        type: string
        description: 'Checkout Git submodules or not'
        default: 'false'
      default_branch:
        required: true
        type: string
        description: 'Default branch name'
    secrets:
      gh_token:
        required: true
        description: 'GitHub token'
jobs:
  sync-develop:
    -
      uses: actions/checkout@v2
      name: Checkout code
      with:
        ref: ${{ inputs.git_ref }}
        fetch-depth: 0
        submodules: ${{ inputs.submodules }}
        token: ${{ secrets.gh_token }}
    - 
      name: Up Merge
      uses: bambamboole/gha-upmerge@master
      with:
        stable_branch: ${{ inputs.default_branch }}
        development_branch: 'develop'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}