name: Configure Staging Workflow
on:
  workflow_call:
    outputs:
      settings:
        value: ${{ jobs.configure.outputs.settings }}
        description: Configuration JSON as string
      version:
        value: ${{ jobs.configure.outputs.version }}
        description: Latest released version
jobs:
  configure:
    runs-on: ubuntu-latest
    outputs:
      settings: ${{ steps.settings.outputs.settings }}
      version: ${{ steps.version.outputs.version }}
    steps:
      -
        name: Match version format
        uses: actions-ecosystem/action-regex-match@v2
        id: regex
        with:
          text: ${{ github.ref_name }}
          regex: '^((release|hotfix)\/v[0-9]+.[0-9]+.[0-9]+)$'
      -
        name: Validate version match
        if: steps.regex.outputs.match == ''
        run: |
          echo "Invalid branch name '${{ github.ref_name }}'"
          exit 1
      - 
        name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          token: ${{ secrets.GKS_GH_ACCESS_TOKEN }}
          submodules: false
          fetch-depth: 0
      -
        name: Check branch origin
        id: origin
        run: |
          PREFIX=$(echo '${{ github.ref_name }}' | cut -d '/' -f 1)
          echo $PREFIX
          echo "prefix=$PREFIX" >> $GITHUB_OUTPUT
      #! -
      #!   name: Validate hotfix parent branch
      #!   if: steps.origin.outputs.prefix == 'hotfix'
      #!   run: |
      #!     git checkout ${{ github.event.repository.default_branch }}
      #!     git checkout ${{ github.ref_name }}
      #!     PARENT=$(git show-branch -a | grep '\*' | grep -v `git rev-parse --abbrev-ref HEAD` | head -n1 | sed 's/.*\[\(.*\)\].*/\1/' | sed 's/[\^~].*//')
      #!     echo $PARENT
      #!     if [ $PARENT != '${{ github.event.repository.default_branch }}' ]
      #!     then
      #!       echo "Invalid parent branch '$PARENT', should be '${{ github.event.repository.default_branch }}'"
      #!       exit 2
      #!     fi
      #! -
      #!   name: Validate release parent branch
      #!   if: steps.origin.outputs.prefix == 'release'
      #!   run: |
      #!     BRANCH='develop'
      #!     git checkout $BRANCH
      #!     git checkout ${{ github.ref_name }}
      #!     PARENT=$(git show-branch -a | grep '\*' | grep -v `git rev-parse --abbrev-ref HEAD` | head -n1 | sed 's/.*\[\(.*\)\].*/\1/' | sed 's/[\^~].*//')
      #!     echo $PARENT
      #!     if [ $PARENT != $BRANCH ]
      #!     then
      #!       echo "Invalid parent branch '$PARENT', should be '$BRANCH'"
      #!       exit 3
      #!     fi
      - 
        name: Validate branch
        if: steps.origin.outputs.prefix == ''
        run: |
          echo "Error parsing branch name"
          exit 4
      -
        name: Get version
        id: version
        run: |
          VERSION=$(echo '${{ github.ref_name }}' | sed 's/release\///g' | sed 's/hotfix\///g')
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      - 
        name: Check tag existence
        uses: mukunku/tag-exists-action@v1.0.0
        id: tag
        with: 
          tag: ${{ steps.version.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GKS_GH_ACCESS_TOKEN }}
      -
        name: Fail if tag exists
        if: steps.tag.outputs.exists == 'true'
        run: |
          echo "Release with tag '${{ steps.version.outputs.version }}' already exists"
          exit 5
      # TODO: check if hotfix or release with such version is already created
      -
        name: Read config file
        uses: Geta/gks/actions/read-config-file@actions/v3
        id: settings
        with:
          file: ${{ vars.CONFIG_FILE }}
          ref: ${{ github.ref }}
          gh_token: ${{ secrets.GKS_GH_ACCESS_TOKEN }}
