name: Create release
on:
  workflow_call:
    inputs:
      settings:
        required: true
        type: string
        description: Configuration JSON as string
      version:
        required: true
        type: string
        description: Latest released version
jobs:
  release:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v2
        name: Checkout code
        with:
          ref: ${{ github.ref }}
          token: ${{ secrets.GKS_GH_ACCESS_TOKEN }}
          submodules: false
      -
        name: Create and push tag
        run: |
          git config user.email "gks+gha@getadigital.com"
          git config user.name "gks-release-bot"
          git tag ${{ inputs.version }} -m "${{ github.event.pull_request.title }}"
          git push origin ${{ inputs.version }}
      -
        name: Create Github Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ inputs.version }}
          token: ${{ secrets.GKS_GH_ACCESS_TOKEN }}
          draft: false
          generateReleaseNotes: true
      -
        name: Merge to develop
        uses: everlytic/branch-merge@1.1.2
        with:
          github_token: ${{ secrets.GKS_GH_ACCESS_TOKEN }}
          source_ref: ${{ github.head_ref }}
          target_branch: 'develop'
          commit_message_template: 'Merged {source_ref} into target {target_branch}'