name: Notify end
on:
  workflow_call:
    inputs:
      channel_index:
        required: true
        type: number
        description: Slack channel config index
      phase:
        required: true
        type: number
        description: Build phase index
      result:
        required: true
        type: string
        description: Step result
      slack_artifact_name:
        required: true
        type: string
        description: Github artifact name containing slack template
      slack_template_file:
        required: true
        type: string
        description: Slack message template file name
      slack_template_dir:
        required: false
        type: string
        default: /tmp/slack
        description: Template file directory
      settings:
        required: true
        type: string
        description: Settings json
      matrix_step_name:
        required: true
        type: string
        description: Matrix step name
    outputs:
      slack_state:
        value: ${{ jobs.notify.outputs.slack_state }}
        description: Slack state
      slack_message_id:
        value: ${{ jobs.notify.outputs.slack_message_id }}
        description: Slack message id
jobs:
  read:
    runs-on: ubuntu-latest
    name: Read matrix outputs
    outputs:
      result: "${{ steps.read.outputs.result }}"
    steps:
      - uses: cloudposse/github-action-matrix-outputs-read@main
        id: read
        with:
          matrix-step-name: ${{ inputs.matrix_step_name }}

  notify:
    name: Compose and send Slack message
    runs-on: ubuntu-latest
    needs: [ read ]
    outputs:
      slack_state: ${{ steps.notification.outputs.state }}
      slack_message_id: ${{ steps.slack.outputs.ts }}
    env:
      STATUS_STEP: ""
      MENTION_USER: false
    steps:
      -
        name: Prepare success Slack message
        if: inputs.result == 'success'
        run: |
          STEP=$(echo ":white_check_mark: *${{ fromJson(needs.read.outputs.result).step[fromJson(inputs.settings).notifications.slack.channels[inputs.channel_index].id] }}*")
          echo "STATUS_STEP=$STEP" >> $GITHUB_ENV
      -
        name: Prepare failure Slack message
        if: inputs.result == 'failure'
        run: |
          STEP=$(echo ":x: *${{ inputs.step }}*")
          echo "STATUS_STEP=$STEP" >> $GITHUB_ENV
          echo "MENTION_USER=true" >> $GITHUB_ENV
      -
        name: Prepare cancel Slack message
        if: inputs.result == 'cancelled'
        run: |
          STEP=$(echo ":grey_exclamation: *${{ inputs.step }}*")
          echo "STATUS_STEP=$STEP" >> $GITHUB_ENV
      -
        name: Download notification template
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.slack_artifact_name }}
          path: ${{ inputs.slack_template_dir }}
      -
        name: Add end notification step
        id: notification
        uses: Geta/gks/actions/add-notification-step@actions/v3
        with:
          template_path: ${{ inputs.slack_template_dir }}/${{ inputs.slack_template_file }}
          phase: ${{ inputs.phase }}
          step: ${{ env.STATUS_STEP }}
          state: ${{ inputs.slack_phase_state }}
          mention: ${{ env.MENTION_USER }}
      -
        name: Send Slack notification
        id: slack
        uses: slackapi/slack-github-action@v1
        with:
          channel-id: ${{ fromJson(inputs.settings).notifications.slack.channels[inputs.channel_index].id }}
          payload-file-path: ${{ inputs.slack_template_dir }}/${{ inputs.slack_template_file }}
        env:
          SLACK_BOT_TOKEN: ${{ secrets.GKS_GCC_SLACK_BOT_TOKEN }}