name: Run Preconfiguration
on:
  workflow_call:
    inputs:
      file:
        required: false
        type: string
        description: 'Configuration file path'
        default: '.github/config.yaml'
jobs:
  collect-info:
    runs-on: ubuntu-latest
    outputs:
      app_name: '${{ steps.appname.outputs.data }}'
      dockerfile: '${{ steps.dockerfile.outputs.data }}'
    steps:
      -
        name: Read application name
        uses: KJ002/read-yaml@1.5
        id: appname
        with:
          file: '${{ inputs.file }}'
          key-path: '["app", "name"]'
      -
        name: Read application name
        uses: KJ002/read-yaml@1.5
        id: dockerfile
        with:
          file: '${{ inputs.file }}'
          key-path: '["app", "dockerfile"]'