name: Publish Web Assets
on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string
        description: Environment name
      version:
        required: true
        type: string
        description: Version number
      app_index:
        required: true
        type: number
        description: App settings index
      settings:
        required: true
        type: string
        description: JSON settings string
jobs:
  setup:
    name: Set up notifications
    uses: Geta/gks/.github/workflows/configure-notifications.yaml@workflows/v3
    secrets: inherit
    with:
      app_index: ${{ inputs.app_index }}
      version: ${{ inputs.version }}
      settings: ${{ inputs.settings }}
      initial_state: |
        :hourglass: *Docker image*
        :grey_question: *Helm chart*

  publish-docker:
    name: Publish Docker image
    needs: [ setup ]
    uses: Geta/gks/.github/workflows/publish-docker.yaml@workflows/v3
    secrets: inherit
    with:
      phase: 0
      app_index: ${{ inputs.app_index }}
      env: ${{ inputs.env }}
      version: ${{ inputs.version }}
      settings: ${{ inputs.settings }}
      slack_artifact_name: ${{ needs.setup.outputs.artifact }}
      slack_template_file: ${{ needs.setup.outputs.template_file }}
      slack_phase_state: ${{ needs.setup.outputs.phase_state }}
      args: |
        PACKAGES_URL=${{ fromJson(inputs.settings).artifacts.npm.repoUrl }}

  publish-helm:
    name: Publish Helm chart
    needs: [ setup, publish-docker ]
    uses: Geta/gks/.github/workflows/publish-helm.yaml@workflows/v3
    secrets: inherit
    with:
      phase: 1
      app_index: ${{ inputs.app_index }}
      env: ${{ inputs.env }}
      version: ${{ inputs.version }}
      settings: ${{ inputs.settings }}
      image_name: ${{ needs.publish-docker.outputs.image_name }}
      image_tag: ${{ needs.publish-docker.outputs.image_tag }}
      slack_artifact_name: ${{ needs.setup.outputs.artifact }}
      slack_template_file: ${{ needs.setup.outputs.template_file }}
      slack_phase_state: ${{ needs.publish-docker.outputs.slack_state }}
      slack_message_id: ${{ needs.publish-docker.outputs.slack_message_id }}