name: Publish clients
on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string
        description: Environment name
      version:
        required: true
        type: string
        description: Version number
      settings:
        required: true
        type: string
        description: Settings json string
jobs:
  publish-npm:
    if: ${{ fromJson(inputs.settings).clients.publish.npm }}
    name: Publish NPM package
    uses: Geta/gks/.github/workflows/publish-npm.yaml@v5
    secrets: inherit
    with:
      env: ${{ inputs.env }}
      version: ${{ inputs.version }}
      settings: ${{ inputs.settings }}

  publish-nuget:
    if: ${{ fromJson(inputs.settings).clients.publish.nuget }}
    name: Publish NuGet package
    uses: Geta/gks/.github/workflows/publish-nuget.yaml@v5
    secrets: inherit
    with:
      env: ${{ inputs.env }}
      version: ${{ inputs.version }}
      settings: ${{ inputs.settings }}