name: Sync Assets
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.githooks/**'
      - '.github/actions/**'
      - '.github/workflows/templates/**'
jobs:
  sync-assets:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          token: ${{ secrets.GKS_GH_ACCESS_TOKEN }}
      - 
        name: Sync assets
        uses: varunsridharan/action-github-workflow-sync@89079da42f314fe368ef09d4ab0223c8612213ab
        with:
          DRY_RUN: true
          SKIP_CI: false
          REPOSITORIES: |
            Geta/gks-tenant-gcc@main
          WORKFLOW_FILES: |
            .githooks=.githooks
            .github/actions=.github/actions
            .github/workflows/templates=.github/workflows/shared
          GITHUB_TOKEN: ${{ secrets.GKS_GH_ACCESS_TOKEN }}
          COMMIT_MESSAGE: 'GKS Automated Asset Sync'